files:
- generatedChecksum: 39FF52903D784BEF79D3640DC1072AFA
  logicalPath: config\pic32mz_ef_sk
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 39FF52903D784BEF79D3640DC1072AFA
- generatedChecksum: 94688D065E4679553EAC58962EAF4C6D
  logicalPath: config\pic32mz_ef_sk
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 94688D065E4679553EAC58962EAF4C6D
- generatedChecksum: 4B6A778CF4449A8EC938F5D4D0917E56
  logicalPath: config\pic32mz_ef_sk
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 4B6A778CF4449A8EC938F5D4D0917E56
- generatedChecksum: null
  logicalPath: ''
  name: main.c
  physicalPath: ..\..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: 5EBDC08BAE72DD04701C9753F538FD62
  logicalPath: config\pic32mz_ef_sk\peripheral\clk
  name: plib_clk.c
  physicalPath: peripheral\clk
  security: NON_SECURE
  type: SOURCE
  userChecksum: 5EBDC08BAE72DD04701C9753F538FD62
- generatedChecksum: DCDD2CA75B49768C6F79ADE491F5AA0F
  logicalPath: config\pic32mz_ef_sk\peripheral\ebi
  name: plib_ebi.c
  physicalPath: peripheral\ebi
  security: NON_SECURE
  type: SOURCE
  userChecksum: DCDD2CA75B49768C6F79ADE491F5AA0F
- generatedChecksum: ED6722C1169FEA2DA1F15D907F42AA46
  logicalPath: config\pic32mz_ef_sk\peripheral\evic
  name: plib_evic.c
  physicalPath: peripheral\evic
  security: NON_SECURE
  type: SOURCE
  userChecksum: ED6722C1169FEA2DA1F15D907F42AA46
- generatedChecksum: 7FE3F440D09D92D0AAAFFAA0099E8C97
  logicalPath: config\pic32mz_ef_sk\peripheral\gpio
  name: plib_gpio.c
  physicalPath: peripheral\gpio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 7FE3F440D09D92D0AAAFFAA0099E8C97
- generatedChecksum: 7806B30ECAE0D18D08CD583D8775530D
  logicalPath: config\pic32mz_ef_sk\stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 7806B30ECAE0D18D08CD583D8775530D
- generatedChecksum: FF08F4CF197FA213ECCB435F6B80F489
  logicalPath: config\pic32mz_ef_sk
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: FF08F4CF197FA213ECCB435F6B80F489
- generatedChecksum: E189C26B2269F8DE46033CCD0621958D
  logicalPath: config\pic32mz_ef_sk
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: E189C26B2269F8DE46033CCD0621958D
- generatedChecksum: 4CF4A86296482D5331331BA301C20BB2
  logicalPath: config\pic32mz_ef_sk
  name: interrupts.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 4CF4A86296482D5331331BA301C20BB2
- generatedChecksum: 7066CC390335CF75126E2A50C46E3BDD
  logicalPath: config\pic32mz_ef_sk\peripheral\clk
  name: plib_clk.h
  physicalPath: peripheral\clk
  security: NON_SECURE
  type: HEADER
  userChecksum: 7066CC390335CF75126E2A50C46E3BDD
- generatedChecksum: 2FB4AA3D9381D5DACF95B3338F5A3125
  logicalPath: config\pic32mz_ef_sk\peripheral\ebi
  name: plib_ebi.h
  physicalPath: peripheral\ebi
  security: NON_SECURE
  type: HEADER
  userChecksum: 2FB4AA3D9381D5DACF95B3338F5A3125
- generatedChecksum: 3C465EE2268CD765C11300F75C6560CC
  logicalPath: config\pic32mz_ef_sk\peripheral\evic
  name: plib_evic.h
  physicalPath: peripheral\evic
  security: NON_SECURE
  type: HEADER
  userChecksum: 3C465EE2268CD765C11300F75C6560CC
- generatedChecksum: B25B48C4F2E9D579D8C29BA5D0DFB438
  logicalPath: config\pic32mz_ef_sk\peripheral\gpio
  name: plib_gpio.h
  physicalPath: peripheral\gpio
  security: NON_SECURE
  type: HEADER
  userChecksum: B25B48C4F2E9D579D8C29BA5D0DFB438
- generatedChecksum: FA212DEAE39D4E86EF4E6CB440610FE9
  logicalPath: config\pic32mz_ef_sk
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: FA212DEAE39D4E86EF4E6CB440610FE9
- generatedChecksum: 0874C33222DE6210BE6D505E600ED93F
  logicalPath: config\pic32mz_ef_sk
  name: p32MZ2048EFH144.ld
  physicalPath: ''
  security: NON_SECURE
  type: LINKER
  userChecksum: 0874C33222DE6210BE6D505E600ED93F
format_version: v1.0
libraries: []
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mz_ef_sk;../src/packs/PIC32MZ2048EFH144_DFP;
- append: false
  category: C32
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32-LD
  delimiter: ;=
  key: preprocessor-macros
  security: NON_SECURE
  value: ''
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mz_ef_sk;../src/packs/PIC32MZ2048EFH144_DFP;
- append: false
  category: C32CPP
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
sourcePaths: []
